def count_symbols(s):
    A_count = 0
    C_count = 0
    G_count = 0
    T_count = 0
    for symbol in s:
        if symbol == 'A':
            A_count += 1
        elif symbol == 'C':
            C_count += 1
        elif symbol == 'G':
            G_count += 1
        elif symbol == 'T':
            T_count += 1
    return ' '.join(str(i) for i in [A_count, C_count, G_count, T_count])

s = "TCACCTGTGCTGAGAGAAGACAGAGTCAACGGTGATTATGGGCCTTTTCTTACTATTGACCTAGACTAGTGCAGGCACCCCCCTACCTTGGATACAGGCATCACACGATTGCCTTTCATTAGCTACTCGTTAATTAGGTTGGGCCCCACGCTTCTCCCCGCTGTAAGACAGCTGCCTTGCTCTGGTTTTGCGGTTTGGTTTAGGGACGTATCGACGCTTGGTTCATCCTAGCACACCCCTTTCTGCCCGACTCGTGAGATAGTTCGCGTTCTCAGAGATACTGGGAACTCAAGATCACTTCCACTGCGAGGTGATCAAAGTCGTAGGGTTATCCCTGTTTGCACATCTGTGGATGGATCTCTAGGGATGTGCCTGAGGCTTGACCGGAACATACCAGATAACGACAATAGCGTTCCTCTGGAGAACAGACACGCAATCCTATATATTCCCTGTCTGTCATAAATCAGACCGATGAATGGGCAATCCTCCCACCCTTTCAGGGAGGCGTCCCGGAGGATGACTGCGAATACCATCGGAGAATCGCTTTCTAGACGCTGCCGTGTAACCACGAATCTCGAACATGGGCTGTTGCGGTCGGTGATGGGCTCCTTCGTACCGATTAGCATTAAAATAGATCGCTAAGGTTCTTCTAGTGAGTACTTATGACTTTAGGATACAGATCGGGACACATGGTACGCCTACCGCCGCATACATTTTCTTTGCCTCGGTAAAAGTGTCCCTAGCGACGGCCAGGCTTTTTGTGGCGAAGTCCACATGCGCGCGCGGGATAGACAGAGCCATTACATTGTCGCACAAATCACCATCATGATAGTATTAAGATCTCCGAGCGGTATCAATGTGGTGGGTATTGGATTGCTAAAATGGCCCGCCACTTTAGTTGATACGAACGCACTTATAAACTGATTATGCGAGATCCCATGCTTAGCCAATTAGCGGCGAGTTGGCTCGAGGTTTGGGACGCTAAGGGTGTTCTAT"
print(count_symbols(s))
